webtalk_init -webtalk_dir F:/Coding Projects/VHDL/ecgr-4146-labs/manchester-encoding/manchester-encoding.sim/sim_1/behav/xsim/xsim.dir/ManchesterEncoding_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 31 14:06:53 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c5486413-b4ed-4e02-8f1f-c016f3c41d07" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c71ca4bae220434aad0216c3208d2f0b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6576_KB" -context "xsim\\usage"
webtalk_transmit -clientid 821087840 -regid "" -xml F:/Coding Projects/VHDL/ecgr-4146-labs/manchester-encoding/manchester-encoding.sim/sim_1/behav/xsim/xsim.dir/ManchesterEncoding_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Coding Projects/VHDL/ecgr-4146-labs/manchester-encoding/manchester-encoding.sim/sim_1/behav/xsim/xsim.dir/ManchesterEncoding_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Coding Projects/VHDL/ecgr-4146-labs/manchester-encoding/manchester-encoding.sim/sim_1/behav/xsim/xsim.dir/ManchesterEncoding_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
